### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by mharbb** [PatemaAelita/HeyItsTimeToStop#1]
Does this start the server back up when you try to connect? if not what means are there to do so?

**Comment by PatemaAelita** [comment]
> Does this start the server back up when you try to connect? if not what means are there to do so?

Hi there!!
No this mod is made to stop your server when nobody is connected for a custom amount of time (15minutes by derfault). To start the server when you're trying to connect you can use [LazyMC](https://github.com/timvisee/lazymc)!

**Comment by mharbb** [comment]
> > Does this start the server back up when you try to connect? if not what means are there to do so?
> 
> 
> 
> Hi there!!
> 
> No this mod is made to stop your server when nobody is connected for a custom amount of time (15minutes by derfault). To start the server when you're trying to connect you can use [LazyMC](https://github.com/timvisee/lazymc)!

Thankk's I have been trying to find something like lazy mc for a while now will check it out.
